### ISSUE TITLE
Buffer polyfill leads to "window is not defined"

### ISSUE THREAD

**Issue by slavanga** [Uniswap/widgets#133] opened 2022-08-10 16:16 UTC
**Bug Description**
The [Buffer polyfill](https://github.com/Uniswap/widgets/blob/main/src/polyfills.ts) added for the wallet connect feature uses the window object.
This leads to the following error in React: **ReferenceError: window is not defined** 

**Steps to Reproduce**
Import the Uniswap widget in a React / Next.js app

**Comment by mstoyanovv** [comment] 2022-08-12 07:45
If you are using Next.js this error is caused by the component server rendering. To fix it you can import the component in which uniswap is used with ssr disabled : 

```
import dynamic from 'next/dynamic'

const DynamicHeader = dynamic(() => import('../components/header'), {
  ssr: false,
})
```

**Comment by slavanga** [comment] 2022-08-12 07:58
@mstoyanovv How would that work in the specific example of Uniswap? Trying to export multiple members. My import looks like this:
```js
import {
  DefaultAddress,
  SwapWidget,
  Theme,
  TokenInfo,
} from '@uniswap/widgets';
```

**Comment by mstoyanovv** [comment] 2022-08-12 08:34
> @mstoyanovv How would that work in the specific example of Uniswap? Trying to export multiple members. My import looks like this:
> 
> ```js
> import {
>   DefaultAddress,
>   SwapWidget,
>   Theme,
>   TokenInfo,
> } from '@uniswap/widgets';
> ```

Create a new component(ex: MyUniSwapWidget) that holds the uniswap widget and uses the import that you specified. Then from your main component(ex: MainPage) do a dynamic import for MyUniSwapWidget

**Comment by slavanga** [comment] 2022-08-12 15:24
@mstoyanovv thanks, that could work.
I still think it's an antipattern to just access the window object without any conditions.

**Comment by zzmp** [comment] 2022-09-14 23:37
Closing as a duplicate of #146

**Closed by zzmp** 2022-09-14 23:37 UTC
Labels: bug
