### ISSUE TITLE
Popovers broken on small screens

### ISSUE THREAD

**Issue by slavanga** [Uniswap/widgets#166] opened 2022-08-24 08:01 UTC
**Bug Description**
Popovers are broken on small screens (see screenshots).

![broken-popover](https://user-images.githubusercontent.com/1077807/186364046-24513af1-e8d2-4447-a4b0-4ff9537beb90.png)

**Steps to Reproduce**

1. Click on the settings icon
2. Click on one of the question mark icons

**Expected Behavior**
Popovers should use the whole width

**Comment by akarys92** [comment] 2022-09-14 22:17
@slavanga Can you clarify what screen size you're using to reproduce? I'm unable to reproduce on a 300px screen size.

**Comment by zzmp** [comment] 2022-09-14 23:36
I believe I fixed this issue. @slavanga can you confirm if this is resolved in your project after you've upgraded to at least v2.8.1?

**Comment by slavanga** [comment] 2022-09-15 06:10
@zzmp looks good in the [demo widget](https://docs.uniswap.org/sdk/widgets/swap-widget)  🙌

**Closed** 2022-12-09 13:50 UTC
Labels: bug
